"""empty message

Revision ID: b1f8b263b250
Revises: d76cc0a4c7c9
Create Date: 2023-08-20 16:45:09.101989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f8b263b250'
down_revision = 'd76cc0a4c7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(length=20), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
